### ISSUE TITLE
Setup Bigwigs Packager GitHub Action

### ISSUE THREAD

**Issue by Gogo1951** [Davie3/who-taunted#30]
https://github.com/BigWigsMods/packager

1 =====

Get an API token from CurseForge.

Call it whatever you want, you just need to copy the API Key.

https://cdn.discordapp.com/attachments/958740501601849394/1022479579543257108/unknown.png

2 =====

Add the API Key to a Secret in Github called "CF_API_KEY"

https://cdn.discordapp.com/attachments/958740501601849394/1022479914571681812/unknown.png

3 =====

Create a file for the Github Action code.

> .github/workflows/package.yml

Add this code to call the BigWigsMods package manager for Wrath; no changes needed to this block.

```
name: Package Addon

on:
  push:
    branches: [ main ]
    tags: [ "*" ]

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Package and release Wrath
        uses: BigWigsMods/packager@master
        with:
          args: -g wrath
```

https://cdn.discordapp.com/attachments/958740501601849394/1022480328390094848/unknown.png

4 =====

Grab the Project ID off your CurseForge page.

https://cdn.discordapp.com/attachments/958740501601849394/1022480599824470047/unknown.png

5 =====

Add the CurseForge Project ID to your TOC file. 

Replace ###### with your Project ID.

> ## X-Curse-Project-ID: ######

https://cdn.discordapp.com/attachments/958740501601849394/1022480850241212446/unknown.png

6 =====

That's it!

Any time you tag a release presto you're just out there. CurseForge, and also works with WoWUp and whatever else.

Note: Anything in your main branch will also show up as an Alpha Release.
